import React, { useRef } from 'react';
import { useLanguage } from '@/hooks/useLanguage';

interface JSONInputCardProps {
  jsonFile: File | null;
  onFileChange: (file: File | null, content: string) => void;
  pastedJson: string;
  onPastedJsonChange: (text: string) => void;
}

export default function JSONInputCard({
  jsonFile,
  onFileChange,
  pastedJson,
  onPastedJsonChange,
}: JSONInputCardProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { language } = useLanguage();
  const isAr = language === 'ar';

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) {
      onFileChange(null, '');
      return;
    }
    const reader = new FileReader();
    reader.onload = (event) => {
      onFileChange(file, event.target?.result as string || '');
    };
    reader.readAsText(file);
  };

  const handleClearFile = () => {
    onFileChange(null, '');
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 flex flex-col gap-4">
      <div>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100">
          {isAr ? 'مدخلات JSON' : 'JSON Input'}
        </h3>
        <p className="text-sm text-slate-500 dark:text-slate-400 mt-1 font-sans">
          {isAr ? 'توفير ملف JSON مخصص تم توليده بواسطة الذكاء الاصطناعي (اختياري).' : 'Optionally provide custom JSON generated by AI.'}
        </p>
      </div>

      <div className="flex flex-col gap-4">
        {/* Upload File */}
        <div className="flex flex-col gap-1.5">
          <label className="text-xs font-semibold text-slate-500 dark:text-slate-400">
            {isAr ? 'رفع ملف JSON' : 'Upload JSON File'}
          </label>
          <div className="flex items-center gap-2">
            <input
              type="file"
              accept=".json"
              ref={fileInputRef}
              onChange={handleFileChange}
              className="hidden"
            />
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              className="flex-1 bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-350 text-xs font-semibold px-3 py-2 rounded-xl text-left truncate flex items-center justify-between cursor-pointer"
            >
              <span className="truncate">{jsonFile ? jsonFile.name : (isAr ? 'اختر ملف .json...' : 'Select .json file...')}</span>
              <span className="text-xs text-slate-400">📁</span>
            </button>
            {jsonFile && (
              <button
                type="button"
                onClick={handleClearFile}
                className="bg-red-50 hover:bg-red-100 dark:bg-red-950/20 dark:hover:bg-red-950/50 text-red-650 dark:text-red-400 border border-red-200 dark:border-red-900/50 text-xs font-semibold px-3 py-2 rounded-xl cursor-pointer"
              >
                {isAr ? 'مسح' : 'Clear'}
              </button>
            )}
          </div>
        </div>

        {/* Paste JSON */}
        <div className="flex flex-col gap-1.5">
          <label className="text-xs font-semibold text-slate-500 dark:text-slate-400">
            {isAr ? 'لصق JSON (اختياري)' : 'Paste JSON (Optional)'}
          </label>
          <textarea
            rows={4}
            value={pastedJson}
            onChange={(e) => onPastedJsonChange(e.target.value)}
            placeholder={isAr ? 'الصق استجابة JSON المستلمة من الذكاء الاصطناعي مباشرة هنا...' : 'Paste the JSON returned by the AI directly here...'}
            className="w-full bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 px-3 py-2 rounded-xl focus:outline-none focus:border-slate-400 dark:focus:border-slate-700 font-mono text-[11px] leading-relaxed resize-y"
          />
          <span className="text-[10px] text-slate-400 dark:text-slate-500 font-sans">
            {isAr ? 'الصق كود JSON المولد هنا.' : 'Paste the JSON returned by the AI here.'}
          </span>
        </div>
      </div>
    </div>
  );
}
